Added fixes

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -33,8 +33,26 @@ jobs:
         with:
           required-ros-distributions: ${{ matrix.ros_distribution }}
       - name: install_clang_and_tools
-        run: apt update && sudo apt install -y clang clang-tools lld wget python3-pip lcov
-      - name: build
+        run: sudo apt update && sudo apt install -y clang clang-tools lld wget python3-pip python3-colcon-coveragepy-result python3-colcon-lcov-result lcov
+      # TODO: fix for cryptography>2.8 failing in galactic https://github.com/open-rmf/rmf/pull/202#pullrequestreview-1100045417
+      - name: fix cryptography==2.8 # https://github.com/open-rmf/rmf/pull/202#pullrequestreview-1100045417
+        run: pip3 install cryptography==2.8
+        if: ${{ matrix.ros_distribution == 'galactic' || matrix.ros_distribution == 'foxy' }}
+      # TODO: remove this when uncrustify 0.72 is fixed https://github.com/uncrustify/uncrustify/issues/3191
+      - name: hack for uncrustify 0.72 problems
+        run: wget http://mirrors.kernel.org/ubuntu/pool/universe/u/uncrustify/uncrustify_0.69.0+dfsg1-1build1_amd64.deb && dpkg -i uncrustify_0.69.0+dfsg1-1build1_amd64.deb && apt install -f -y
+        if: ${{ matrix.ubuntu_distribution == 'jammy'}}
+      # TODO: Remove this step when the incompatibility between libunwind14 and libundind dissapears https://github.com/open-rmf/rmf_traffic_editor/issues/439
+      - name: Horrible hack for libceres
+        run: |
+          apt-get remove -y --purge libc++-dev || true 
+          apt-get remove -y --purge libc++abi-dev || true
+          apt-get remove -y --purge libunwind-14-dev || true 
+          apt-get remove -y --purge libunwind-14-dev || true 
+          apt-get remove -y --purge libunwind-dev || true
+          apt -y autoremove
+        if: ${{ matrix.ubuntu_distribution == 'jammy'}}
+      - name: build_and_test
         uses: ros-tooling/action-ros-ci@v0.2
         with:
           target-ros2-distro: ${{ matrix.ros_distribution }}
